---

- name: Include set responder defaults tasks
  include_tasks: set_responder_defaults.yaml

- name: Include set initiator defaults tasks
  include_tasks: set_initiator_defaults.yaml

- name: Include provision responder tasks if needed
  include_tasks: provision_responder.yaml
  when: cloud_vpn_responder_provisioner_role is defined

- name: Include provision initiator tasks if needed
  include_tasks: provision_initiator.yaml
  when: cloud_vpn_initiator_provisioner_role is defined

- name: Include configure vpn responder tasks
  include_tasks: configure_vpn_responder.yaml

- name: Include configure vpn initiator tasks
  include_tasks: configure_vpn_initiator.yaml

- name: Include configure routing responder tasks
  include_tasks: configure_routing_responder.yaml

- name: Include confgiure routing initiator tasks
  include_tasks: configure_routing_initiator.yaml

- name: Include show login info tasks
  include_tasks: show_login_info.yaml
