---

- name: Include initiator deprovision tasks
  include_tasks: "provisioners/{{ cloud_vpn_initiator_provisioner }}/initiator/deprovision.yaml"
  when: cloud_vpn_initiator_provisioner is defined

- name: Include responder deprovision tasks
  include_tasks: "provisioners/{{ cloud_vpn_responder_provisioner }}/responder/deprovision.yaml"
  when: cloud_vpn_responder_provisioner is defined
