---

- name: Include responder role deprovision tasks
  include_role:
    name: "{{ cloud_vpn_responder_provisioner_role }}"
    tasks_from: "{{ cloud_vpn_responder_provisioner }}/responder/deprovision"
