---

- name: Include create VPN tasks
  include_tasks: create_vpn.yaml
  when: cloud_vpn_state == 'present'

- name: Include delete VPN tasks
  include_tasks: delete_vpn.yaml
  when: cloud_vpn_state == 'absent'
