---

- name: Include post configure initiator hooks tasks
  include_tasks: "{{ cloud_vpn_initiator_post_configure_hooks }}"
  when: cloud_vpn_initiator_post_configure_hooks is defined

- name: Include post configure initiator hooks role
  include_role:
    name: "{{ cloud_vpn_initiator_post_configure_hooks_role }}"
  when: cloud_vpn_initiator_post_configure_hooks_role is defined
