---

- name: Show responder IP and user
  debug:
    msg: "Responder can be reached at {{ cloud_vpn_responder_user}}@{{ cloud_vpn_responder_public_ip }}"
  when: cloud_vpn_responder_user is defined

- name: Show initiator IP and user
  debug:
    msg: "Initiator can be reached at {{ cloud_vpn_initiator_user}}@{{ cloud_vpn_initiator_public_ip }}"
  when: cloud_vpn_initiator_user is defined
