---
- name: Add initiator host
  add_host:
    name: initiator
    ansible_host: "{{ cloud_vpn_initiator_public_ip }}"
    ansible_user: "{{ cloud_vpn_initiator_user }}"
    ansible_connection: network_cli
    ansible_network_os: vyos

- name: Wait for SSH port to be reachable
  wait_for:
    host: "{{ cloud_vpn_initiator_public_ip }}"
    port: 22

- name: Pause for SSH daemon to settle and accept connections
  pause:
    seconds: "{{ cloud_vpn_pause_before_config_seconds }}"

- name: Push configuration to VyOS device
  vyos_config:
    src: "providers/vyos/initiator/{{ cloud_vpn_responder_provider }}/configure_{{ cloud_vpn_routing }}.j2"
  delegate_to: initiator
