---
- add_host:
    name: initiator
    ansible_host: "{{ cloud_vpn_initiator_ip }}"
    ansible_user: "{{ cloud_vpn_initiator_user }}"
    ansible_connection: network_cli
    ansible_network_os: ios

- ios_config:
    src: "csr/initiator/{{ peer_type_to_config[cloud_vpn_responder_type] }}/configure_static.j2"
  delegate_to: initiator
