---
- name: Add responder host
  add_host:
    name: responder
    ansible_host: "{{ cloud_vpn_responder_ip }}"
    ansible_user: "{{ cloud_vpn_responder_user }}"
    ansible_connection: network_cli
    ansible_network_os: vyos

- name: Wait for SSH port to be reachable
  wait_for:
    host: "{{ cloud_vpn_responder_ip }}"
    port: 22

- name: Pause for SSH daemon to settle and accept connections
  pause:
    seconds: "{{ cloud_vpn_pause_before_config_seconds }}"

- name: Push configuration to VyOS device
  vyos_config:
    src: "vyos/responder/{{ peer_type_to_config[cloud_vpn_initiator_type] }}/configure_{{ cloud_vpn_routing_type }}.j2"
  delegate_to: responder
